In [1]:
import requests
import polyline
import json
import pandas as pd
from shapely.geometry import Point
import folium
import geopandas as gpd
import dotenv
import os
import matplotlib.pyplot as plt
from openrouteservice import convert
from geopy.distance import geodesic
import numpy as np
import math
import time

In [2]:
dotenv.load_dotenv()
ORS_API_KEY=os.getenv('ORS_API_KEY')
AZURE_API_KEY=os.getenv('AZURE_API_KEY')
AZURE_API_KEY_2=os.getenv('AZURE_API_KEY_2')

In [6]:
# [Lat,lon] format
def generate_map(coords):
    m=folium.Map(location=coords[0], zoom_start=12)
    folium.Marker(coords[0]).add_to(m)
    folium.Marker(coords[-1]).add_to(m)
    folium.PolyLine(
        coords,
        color="blue",
        weight=5,
        opacity=0.8
    ).add_to(m)
    return m

#line=convert.decode_polyline(ors["routes"][0]["geometry"],False)
#generate_map([[lat,lon]for lon,lat in line["coordinates"]])

In [3]:
amva = pd.read_json("matrix/amva_traffic.json")

In [4]:
row = amva.iloc[0]

In [7]:
def get_alt(coordinates, api_key):
    url = "https://api.openrouteservice.org/elevation/line"
    headers = {
        "Authorization": api_key,
        "Content-Type": "application/json"
    }

    # ORS espera formato lat, lon para ENCODED_POLYLINE
    geometry_latlng = [(lat, lng) for lng, lat in coordinates]

    payload = {
        "format_in": "encodedpolyline",
        "format_out": "geojson",
        "geometry": polyline.encode(geometry_latlng)
    }

    response = requests.post(url, headers=headers, json=payload)
    if response.status_code != 200:
        raise Exception(f"Error elevación: {response.text}")
    data = response.json()
    return data['geometry']['coordinates']

In [49]:
# lon, lat format
def get_route(coords,api_key):
    url = "https://api.openrouteservice.org/v2/directions/driving-car"
    headers = {
        "Authorization": api_key,
        "Content-Type": "application/json"
    }
    payload = {
        "coordinates": coords,
        "instructions": True,
        "elevation":True
    }

    response = requests.post(url, json=payload, headers=headers)
    if response.status_code != 200:
        raise Exception(f"Error elevación: {response.text}")
    
    data = response.json()
    return data

In [9]:
# lon lat
def get_opt_route(coords,time,api_key):
    features = []
    for idx, (lon, lat) in enumerate(coords):
        point_type = "waypoint" if idx in (0, len(coords) - 1) else "viaWaypoint"
        features.append({
            "type": "Feature",
            "geometry": {
                "coordinates": [lon, lat],
                "type": "Point"
            },
            "properties": {
                "pointIndex": idx,
                "pointType": point_type
            }
        })
    date = "2025-09-01T" + time + "-05:00" 

    body = {
        "type": "FeatureCollection",
        "features": features,
        "optimizeRoute": "fastestWithTraffic",
        "routeOutputOptions": ["itinerary","routePath"],
        "maxRouteCount": 1,
        "travelMode": "driving",
        "departAt": date
    }

    url = "https://atlas.microsoft.com/route/directions"
    params = {"api-version": "2025-01-01"}

    response = requests.post(
        url,
        params=params,
        headers={
            "Content-Type": "application/json; charset=UTF-8",
            "subscription-key": api_key
        },
        json=body
    )
    response.raise_for_status()
    return response.json()

In [10]:
# Unidades de metros y segundos 
def get_vel_azure(features,elevation_data):
    route = {
        "coords":[],
        "speed_ms":[],
        "slope_deg":[],
        "time":[],
        "distance":[]
        }
    
    total_time = 0
    total_distance = 0

    for feature in features:
        props = feature["properties"]
        steps = props.get("steps", [])

        for step in steps:
            start_idx, end_idx = step["routePathRange"]["range"]

            step_duration = props.get("durationInSeconds", 0)
            step_distance = props.get("distanceInMeters", 0)
            num_points = end_idx - start_idx

            if num_points <= 0:
                continue

            duration_per_point = step_duration / num_points
            distance_per_point = step_distance / num_points
            
            for i in range(num_points):
                idx = start_idx + i
                
                lng, lat, alt = elevation_data[idx]

                if len(route["coords"]) > 0:
                    prev_lng, prev_lat, prev_alt = route["coords"][-1]
                else:
                    prev_lng, prev_lat, prev_alt = lng, lat, alt

                horiz_dist = geodesic((prev_lat, prev_lng), (lat, lng)).meters

                delta_alt = alt - prev_alt

                slope_deg = math.degrees(math.atan2(delta_alt, horiz_dist)) if horiz_dist != 0 else 0

                speed_ms = (distance_per_point / duration_per_point) if duration_per_point != 0 else 0

                prev_alt = route["coords"][-1][2] if len(route["coords"]) > 0 else alt

                route["coords"].append([lng, lat, alt])
                route["speed_ms"].append(round(speed_ms, 2))
                route["slope_deg"].append(round(slope_deg, 2))
                route["time"].append(round(total_time, 2))
                route["distance"].append(round(total_distance, 2))

                total_time += duration_per_point
                total_distance += distance_per_point

                if idx == len(elevation_data)-2:
                    lng, lat, alt = elevation_data[-1]
                    delta_alt = alt - prev_alt
                    horiz_dist = geodesic((prev_lat, prev_lng), (lat, lng)).meters
                    slope_deg = math.degrees(math.atan2(delta_alt, horiz_dist)) if horiz_dist != 0 else 0

                    lng, lat, alt = elevation_data[-1]
                    route["coords"].append([lng, lat, alt])
                    route["speed_ms"].append(round((distance_per_point / duration_per_point), 2))
                    route["slope_deg"].append(round(slope_deg, 2))
                    route["time"].append(round(total_time, 2))
                    route["distance"].append(round(total_distance, 2))
    return route

In [50]:
def get_vel(steps, elevation_data):
    route = {
        "coords": [],        # [lng, lat, alt] format
        "speed_ms": [],      # Speed in m/s
        "slope_deg": [],     # Slope in degrees
        "time": [],          # Cumulative time in seconds
        "distance": []       # Cumulative distance in meters
    }
    
    total_time = 0
    total_distance = 0

    for step in steps:
        start_idx, end_idx = step["way_points"]
        step_duration = step["duration"]  
        step_distance = step["distance"]  
        num_points = end_idx - start_idx

        if num_points <= 0:
            continue

        duration_per_point = step_duration / num_points
        distance_per_point = step_distance / num_points

        for i in range(num_points):
            idx = start_idx + i
            
            if idx >= len(elevation_data):
                break
                
            lng, lat, alt = elevation_data[idx]

            if len(route["coords"]) > 0:
                prev_lng, prev_lat, prev_alt = route["coords"][-1]
            else:
                prev_lng, prev_lat, prev_alt = lng, lat, alt

            horiz_dist = geodesic((prev_lat, prev_lng), (lat, lng)).meters

            delta_alt = alt - prev_alt

            slope_deg = math.degrees(math.atan2(delta_alt, horiz_dist)) if horiz_dist != 0 else 0

            speed_ms = (distance_per_point / duration_per_point) if duration_per_point != 0 else 0

            route["coords"].append([lng, lat, alt])
            route["speed_ms"].append(round(speed_ms, 2))
            route["slope_deg"].append(round(slope_deg, 2))
            route["time"].append(round(total_time, 2))
            route["distance"].append(round(total_distance, 2))

            total_time += duration_per_point
            total_distance += distance_per_point

            if idx == len(elevation_data)-2:
                lng, lat, alt = elevation_data[-1]
                delta_alt = alt - prev_alt
                horiz_dist = geodesic((prev_lat, prev_lng), (lat, lng)).meters
                slope_deg = math.degrees(math.atan2(delta_alt, horiz_dist)) if horiz_dist != 0 else 0

                route["coords"].append([lng, lat, alt])
                route["speed_ms"].append(round(speed_ms, 2))
                route["slope_deg"].append(round(slope_deg, 2))
                route["time"].append(round(total_time, 2))
                route["distance"].append(round(total_distance, 2))

    return route

In [2]:
with open("exm.json","r") as f:
        medj = json.load(f)

with open("routes/ors_route.json","r") as f:
        ors = json.load(f);

with open("routes/azure_opt2.geojson","r") as f:
        azure_route = json.load(f);

amva = pd.read_json("results/amva.json")

In [3]:
def get_matriz_od(m):
    rows = []
    for i, row in m.iterrows():   
        for j,destino in m.iterrows():
            if i != j:
                new_row = row.copy()
                if "estacion" in row["municipio_o"]:
                    new_row["hora_o"] = destino["hora_o"]
                    new_row["hora_d"] = destino["hora_d"]
                    new_row["modo_tte"] = destino["modo_tte"]
                    new_row["motivo_viaje"] = destino["motivo_viaje"]
                    
                new_row["municipio_d"] = destino["municipio_o"]
                new_row["comuna_d"] = destino["comuna_o"]
                new_row["d_long"] = destino["o_long"]
                new_row["d_lat"] = destino["o_lat"]
                rows.append(new_row)
    return pd.DataFrame(rows, index=[i for i in range(len(rows))])

In [ ]:
i = 0
#for row in medj[:500]:
#    print(i)
#    i = i + 1
#    if(row.get("route") is not None):
#        continue
#    else:
#        try:
#            coord = [[row["o_long"],row["o_lat"]],[row["d_long"],row["d_lat"]]]
#            # Conseguir la ruta con ORS
#            data = get_route(coord,ORS_API_KEY)
#
#            route_line = data["routes"][0]["geometry"]
#
#            route_data=convert.decode_polyline(route_line, True)["coordinates"]
#            
#            steps = data["routes"][0]["segments"][0]["steps"]
#            
#            # Conseguir la ruta con tráfico
#            data_opt = get_opt_route(coord,row["hora_o"],AZURE_API_KEY)
#            data_opt = data_opt["features"]
#
#            line_coords = data_opt[-1]["geometry"]["coordinates"][0]
#            elevation = get_alt(line_coords,ORS_API_KEY)
#            
#            row["route"] = get_vel(steps,route_data)
#            row["route_opt"] = get_vel_azure(data_opt,elevation)
#        except Exception as e:
#            print(e)

In [4]:
o_long = [
    -75.623833,
    -75.578379,
    -75.605652,
    -75.569288,
    -75.623833,
    -75.569288,
    -75.587470,
    -75.560197,
    -75.560197,
    -75.451106
]

o_lat = [
        6.153929,
        6.162938,
        6.180956,
        6.207983,
        6.253028,
        6.253028,
        6.262037,
        6.289064,
        6.334109,
        6.379154
]

estaciones = ["estacion " + str(i) for i in range(1,11)]

horas = ["08:00:00" for _ in range(10)]

In [5]:
estaciones_df = pd.DataFrame(columns=amva.columns)
estaciones_df["o_long"] = o_long
estaciones_df["o_lat"] = o_lat  
estaciones_df["municipio_o"] = estaciones
estaciones_df["comuna_o"] = estaciones
estaciones_df["hora_o"] = horas

In [27]:
estaciones_df

,municipio_o,comuna_o,hora_o,municipio_d,comuna_d,hora_d,motivo_viaje,modo_tte,o_long,o_lat,d_long,d_lat
0,estacion 1,estacion 1,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.623833,6.153929,NaN,NaN
1,estacion 2,estacion 2,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.578379,6.162938,NaN,NaN
2,estacion 3,estacion 3,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.605652,6.180956,NaN,NaN
3,estacion 4,estacion 4,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.569288,6.207983,NaN,NaN
4,estacion 5,estacion 5,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.623833,6.253028,NaN,NaN
5,estacion 6,estacion 6,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.569288,6.253028,NaN,NaN
6,estacion 7,estacion 7,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.587470,6.262037,NaN,NaN
7,estacion 8,estacion 8,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.560197,6.289064,NaN,NaN
8,estacion 9,estacion 9,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.560197,6.334109,NaN,NaN
9,estacion 10,estacion 10,08:00:00,NaN,NaN,NaN,NaN,NaN,-75.451106,6.379154,NaN,NaN

In [28]:
matrix = pd.read_json("matrix/amva_routes.json")

In [29]:
vistos = {}
for i, row in matrix.iterrows():
    if(vistos.get(row["o_lat"]) != None):
        continue
    vistos[row["o_lat"]] = 1
    for j, estacion in estaciones_df.iterrows():
        if(row["o_lat"] == estacion["o_lat"] and row["o_long"] == estacion["o_long"]):
            continue
        new_row = row.copy()
        new_row["municipio_d"] = estacion["municipio_o"]
        new_row["comuna_d"] = estacion["comuna_o"]
        new_row["d_long"] = estacion["o_long"]
        new_row["d_lat"] = estacion["o_lat"]
        new_row[["slopes","speeds","coords"]] = None
        matrix.loc[len(matrix)] = new_row

        new_row = estacion.copy()
        new_row["municipio_d"] = row["municipio_o"]
        new_row["comuna_d"] = row["comuna_o"]
        new_row["d_long"] = row["o_long"]
        new_row["d_lat"] = row["o_lat"]
        matrix.loc[len(matrix)] = new_row

In [31]:
df = get_matriz_od(estaciones_df)

In [33]:
matrix = pd.concat([matrix, df], ignore_index=True)

In [45]:
matrix = matrix.sort_values(by=["comuna_o","municipio_d"], ignore_index=True)

In [46]:
matrix.head()

,municipio_o,comuna_o,hora_o,municipio_d,comuna_d,hora_d,motivo_viaje,modo_tte,o_long,o_lat,d_long,d_lat,slopes,coords,speeds
0,Medellin,Belen,17:00:00,Barbosa,Urbana Barbosa,17:15:00,Casa,Moto (Acompa√±ante),-75.594047,6.222594,-75.371796,6.415099,"[[0, -3.4, 0.0, 0.0, -4.01, 0.0, 0.0, 0.0, -0....","[[[-75.59403, 6.22269, 1504.5], [-75.59321, 6....","[[4.17, 4.15, 5.57, 5.57, 5.57, 5.57, 5.57, 12..."
1,Medellin,Belen,17:00:00,Barbosa,Urbana Barbosa,17:15:00,Casa,Moto (Acompa√±ante),-75.594047,6.222594,-75.347011,6.429490,"[[0, -3.4, 0.0, 0.0, -4.01, 0.0, 0.0, 0.0, -0....","[[[-75.59403, 6.22269, 1504.5], [-75.59321, 6....","[[4.17, 4.15, 5.57, 5.57, 5.57, 5.57, 5.57, 12..."
2,Medellin,Belen,05:45:00,Barbosa,Urbana Barbosa,06:00:00,Trabajo,Moto (Conductor),-75.591182,6.230922,-75.347011,6.429490,"[[0, 9.86, 0.0, 0.0, 0.0, 0.0, -14.49, 0.0, 0....","[[[-75.59118, 6.23099, 1499.0], [-75.59144, 6....","[[4.14, 7.66, 7.66, 7.66, 7.66, 7.66, 7.66, 7...."
3,Medellin,Belen,05:45:00,Barbosa,Urbana Barbosa,06:00:00,Trabajo,Moto (Conductor),-75.591182,6.230922,-75.371796,6.415099,"[[0, 9.86, 0.0, 0.0, 0.0, 0.0, -14.49, 0.0, 0....","[[[-75.59118, 6.23099, 1499.0], [-75.59144, 6....","[[4.14, 7.66, 7.66, 7.66, 7.66, 7.66, 7.66, 7...."
4,Medellin,Belen,17:00:00,Bello,Bello-Comuna 02,17:15:00,Casa,Moto (Acompa√±ante),-75.594047,6.222594,-75.583397,6.316436,"[[0, -3.4, 0.0, 0.0, -4.01, 0.0, 0.0, 0.0, -0....","[[[-75.59403, 6.22269, 1504.5], [-75.59321, 6....","[[4.17, 4.15, 5.57, 5.57, 5.57, 5.57, 5.57, 12..."

In [25]:
municipios = amva["municipio_o"].unique()
m = pd.DataFrame(columns=amva.columns)
x=22
for i in range(len(municipios)):
    m.loc[len(m)] = amva[amva["municipio_o"]==municipios[i]].iloc[x].values
    m.loc[len(m)] = amva[amva["municipio_o"]==municipios[i]].iloc[x+1].values

In [27]:
m = pd.concat([m,estaciones_df],ignore_index=True)

In [32]:
expand_m = get_matriz_od(m)

In [34]:
expand_m['slopes'] = None
expand_m['coords'] = None
expand_m['speeds'] = None

In [16]:
expand_m = pd.read_json("matrix/amva_traffic.json")

In [ ]:
for i in range(0, len(expand_m), 2):
    print(i)
    rows = expand_m.iloc[i:i+2]

    coords_list = []
    row_indices = []

    for idx, row in rows.iterrows():
        if expand_m.at[idx, "slopes"] is not None:
            continue

        coord = [[row["o_long"], row["o_lat"]], [row["d_long"], row["d_lat"]]]

        # Get route with ORS
        data = get_opt_route(coord,row["hora_o"] ,AZURE_API_KEY_2)
        route_data = data["features"][-1]["geometry"]["coordinates"][0]

        coords_list.append((idx, route_data, data["features"][:-1]))
        row_indices.append(idx)

    if not coords_list:
        print("lop")
        continue

    lop = []
    for _, route_data, _ in coords_list:
        lop.extend(route_data)

    pol = get_alt(lop, ORS_API_KEY)

    # now split back results per route
    cursor = 0
    for idx, route_data, steps in coords_list:
        seg_len = len(route_data)
        coords = pol[cursor: cursor + seg_len]
        cursor += seg_len

        route = get_vel_azure(steps, coords)

        expand_m.at[idx, "slopes"] = route["slope_deg"]
        expand_m.at[idx, "coords"] = route["coords"]
        expand_m.at[idx, "speeds"] = route["speed_ms"]

    time.sleep(1.5)

In [222]:
idx = 657

if expand_m.at[idx, "slopes"] is None:
    row = expand_m.iloc[idx]
    coord = [[row["o_long"], row["o_lat"]], [row["d_long"], row["d_lat"]]]
    
    data = get_opt_route(coord,row["hora_o"] ,AZURE_API_KEY_2)
    route_data = data["features"][-1]["geometry"]["coordinates"][0]

    elevation = get_alt(route_data, ORS_API_KEY)
    steps = data["features"][:-1]
    route = get_vel_azure(steps, elevation)

    expand_m.at[idx, "slopes"] = route["slope_deg"]
    expand_m.at[idx, "coords"] = route["coords"]
    expand_m.at[idx, "speeds"] = route["speed_ms"]

In [23]:
expand_m.to_json("matrix/amva_traffic.json",orient="records")

In [24]:
matrix = pd.read_json("matrix/amva_traffic.json")

In [31]:
matrix["speeds"].isna().sum()

0

In [94]:
for idx, row in matrix.iterrows():
    print(idx)
    if matrix.iloc[idx]['slopes'] is not None and not matrix.iloc[idx].isna()["slopes"]:
        print("lop")
        continue
    else:
        coord = [[row["o_long"], row["o_lat"]], [row["d_long"], row["d_lat"]]]
        # Get route with ORS
        data = get_route(coord, ORS_API_KEY)
        route_line = data["routes"][0]["geometry"]
        route_data = convert.decode_polyline(route_line, True)["coordinates"]
        
        steps = data["routes"][0]["segments"][0]["steps"]
        route = get_vel(steps, route_data)
        
        matrix.at[idx, "slopes"] = [route["slope_deg"]]
        matrix.at[idx, "coords"] = [route["coords"]]
        matrix.at[idx, "speeds"] = [route["speed_ms"]]
        time.sleep(2.5)

0
lop
1
lop
2
lop
3
lop
4
lop
5
lop
6
lop
7
lop
8
lop
9
lop
10
lop
11
lop
12
lop
13
lop
14
lop
15
lop
16
lop
17
lop
18
lop
19
lop
20
lop
21
lop
22
lop
23
lop
24
lop
25
lop
26
lop
27
lop
28
lop
29
lop
30
lop
31
lop
32
lop
33
lop
34
lop
35
lop
36
lop
37
lop
38
lop
39
lop
40
lop
41
lop
42
lop
43
lop
44
lop
45
lop
46
lop
47
lop
48
lop
49
lop
50
lop
51
lop
52
lop
53
lop
54
lop
55
lop
56
lop
57
lop
58
lop
59
lop
60
lop
61
lop
62
lop
63
lop
64
lop
65
lop
66
lop
67
lop
68
lop
69
lop
70
lop
71
lop
72
lop
73
lop
74
lop
75
lop
76
lop
77
lop
78
lop
79
lop
80
lop
81
lop
82
lop
83
lop
84
lop
85
lop
86
lop
87
lop
88
lop
89
lop
90
lop
91
lop
92
lop
93
lop
94
lop
95
lop
96
lop
97
lop
98
lop
99
lop
100
lop
101
lop
102
lop
103
lop
104
lop
105
lop
106
lop
107
lop
108
lop
109
lop
110
lop
111
lop
112
lop
113
lop
114
lop
115
lop
116
lop
117
lop
118
lop
119
lop
120
lop
121
lop
122
lop
123
lop
124
lop
125
lop
126
lop
127
lop
128
lop
129
lop
130
lop
131
lop
132
lop
133
lop
134
lop
135
lop
136
lop
137
lop
138
lop
139
lop
140
lop
141
lop
142
lop
143
lop
144
lop
145
lop
146
lop
147
lop
148
lop
149
lop
150
lop
151
lop
152
lop
153
lop
154
lop
155
lop
156
lop
157
lop
158
lop
159
lop
160
lop
161
lop
162
lop
163
lop
164
lop
165
lop
166
lop
167
lop
168
lop
169
lop
170
lop
171
lop
172
lop
173
lop
174
lop
175
lop
176
lop
177
lop
178
lop
179
lop
180
lop
181
lop
182
lop
183
lop
184
lop
185
lop
186
lop
187
lop
188
lop
189
lop
190
lop
191
lop
192
lop
193
lop
194
lop
195
lop
196
lop
197
lop
198
lop
199
lop
200
lop
201
lop
202
lop
203
lop
204
lop
205
lop
206
lop
207
lop
208
lop
209
lop
210
lop
211
lop
212
lop
213
lop
214
lop
215
lop
216
lop
217
lop
218
lop
219
lop
220
lop
221
lop
222
lop
223
lop
224
lop
225
lop
226
lop
227
lop
228
lop
229
lop
230
lop
231
lop
232
lop
233
lop
234
lop
235
lop
236
lop
237
lop
238
lop
239
lop
240
lop
241
lop
242
lop
243
lop
244
lop
245
lop
246
lop
247
lop
248
lop
249
lop
250
lop
251
lop
252
lop
253
lop
254
lop
255
lop
256
lop
257
lop
258
lop
259
lop
260
lop
261
lop
262
lop
263
lop
264
lop
265
lop
266
lop
267
lop
268
lop
269
lop
270
lop
271
lop
272
lop
273
lop
274
lop
275
lop
276
lop
277
lop
278
lop
279
lop
280
lop
281
lop
282
lop
283
lop
284
lop
285
lop
286
lop
287
lop
288
lop
289
lop
290
lop
291
lop
292
lop
293
lop
294
lop
295
lop
296
lop
297
lop
298
lop
299
lop
300
lop
301
lop
302
lop
303
lop
304
lop
305
lop
306
lop
307
lop
308
lop
309
lop
310
lop
311
lop
312
lop
313
lop
314
lop
315
lop
316
lop
317
lop
318
lop
319
lop
320
lop
321
lop
322
lop
323
lop
324
lop
325
lop
326
lop
327
lop
328
lop
329
lop
330
lop
331
lop
332
lop
333
lop
334
lop
335
lop
336
lop
337
lop
338
lop
339
lop
340
lop
341
lop
342
lop
343
lop
344
lop
345
lop
346
lop
347
lop
348
lop
349
lop
350
lop
351
lop
352
lop
353
lop
354
lop
355
lop
356
lop
357
lop
358
lop
359
lop
360
lop
361
lop
362
lop
363
lop
364
lop
365
lop
366
lop
367
lop
368
lop
369
lop
370
lop
371
lop
372
lop
373
lop
374
lop
375
lop
376
lop
377
lop
378
lop
379
lop
380
lop
381
lop
382
lop
383
lop
384
lop
385
lop
386
lop
387
lop
388
lop
389
lop
390
lop
391
lop
392
lop
393
lop
394
lop
395
lop
396
lop
397
lop
398
lop
399
lop
400
lop
401
lop
402
lop
403
lop
404
lop
405
lop
406
lop
407
lop
408
lop
409
lop
410
lop
411
lop
412
lop
413
lop
414
lop
415
lop
416
lop
417
lop
418
lop
419
lop
420
lop
421
lop
422
lop
423
lop
424
lop
425
lop
426
lop
427
lop
428
lop
429
lop
430
lop
431
lop
432
lop
433
lop
434
lop
435
lop
436
lop
437
lop
438
lop
439
lop
440
lop
441
lop
442
lop
443
lop
444
lop
445
lop
446
lop
447
lop
448
lop
449
lop
450
lop
451
lop
452
lop
453
lop
454
lop
455
lop
456
lop
457
lop
458
lop
459
lop
460
lop
461
lop
462
lop
463
lop
464
lop
465
lop
466
lop
467
lop
468
lop
469
lop
470
lop
471
lop
472
lop
473
lop
474
lop
475
lop
476
lop
477
lop
478
lop
479
lop
480
lop
481
lop
482
lop
483
lop
484
lop
485
lop
486
lop
487
lop
488
lop
489
lop
490
lop
491
lop
492
lop
493
lop
494
lop
495
lop
496
lop
497
lop
498
lop
499
lop
500
lop
501
lop
502
lop
503
lop
504
lop
505
lop
506
lop
507
lop
508
lop
509
lop
510
lop
511
lop
512
lop
513
lop
514
lop
515
lop
516
lop
517
lop
518
lop
519
lop
520
lop
521
lop
522
lop
523
lop
524
lop
525
lop
526
lop
527
lop
528
lop
529
lop
530
lop
531
lop
532
lop
533
lop
534
lop
535
lop
536
lop
537
lop
538
lop
539
lop
540
lop
541
lop
542
lop
543
lop
544
lop
545
lop
546
lop
547
lop
548
lop
549
lop
550
lop
551
lop
552
lop
553
lop
554
lop
555
lop
556
lop
557
lop
558
lop
559
lop
560
lop
561
lop
562
lop
563
lop
564
lop
565
lop
566
lop
567
lop
568
lop
569
lop
570
lop
571
lop
572
lop
573
lop
574
lop
575
lop
576
lop
577
lop
578
lop
579
lop
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869

In [119]:
for i, row in matrix[1:].iterrows():
    matrix.at[i,"slopes"] = row["slopes"][0]
    matrix.at[i,"speeds"] = row["speeds"][0]
    matrix.at[i,"coords"] = row["coords"][0]

In [121]:
matrix.to_json("matrix/amva_routes.json")

In [122]:
m1 = pd.read_json("matrix/amva_routes.json")